server.port=8081

# MySQL database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/skillforge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

jwt.secret=hFZDx5eSueWl+Wgl3x6/9JvVjXo7vOKV8EocJizg25U=
jwt.expiration=86400000

