server.port=8081

# H2 (optional profile) - run with: -Dspring-boot.run.profiles=h2
spring.datasource.url=jdbc:h2:mem:skillforge;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

jwt.secret=hFZDx5eSueWl+Wgl3x6/9JvVjXo7vOKV8EocJizg25U=
jwt.expiration=86400000

